version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails-lesson'
    environment:
      TZ: 'Asia/Tokyo'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      DATABASE_USER: 'postgres'
      DATABASE_NAME: 'rails_lesson_development'
      DATABASE_PASSWORD: 'postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'rails_lesson_development'
    volumes:
      - 'database:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  database:
